import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseAmount, formatAmount, formatDecimal, splitShares, parseHandles } from '../web/js/money.js';

test('parseAmount accepts plain decimals', () => {
  const ok = [
    ['15', 2, 1500], ['15.00', 2, 1500], [' 15.5 ', 2, 1550], ['0.01', 2, 1],
    ['10000000.00', 2, 1000000000], ['1000000000', 0, 1000000000], ['1200', 0, 1200],
    ['1.234', 3, 1234], ['007', 2, 700],
  ];
  for (const [text, mu, minor] of ok) assert.deepEqual(parseAmount(text, mu), { ok: true, minor }, text);
});

test('parseAmount rejects with the right reason', () => {
  const bad = [
    ['', 2, 'empty'], [' ', 2, 'empty'], [null, 2, 'empty'], [undefined, 2, 'empty'],
    ['-5', 2, 'format'], ['+5', 2, 'format'], ['1e3', 2, 'format'], ['1,000', 2, 'format'],
    ['15.', 2, 'format'], ['.5', 2, 'format'], ['abc', 2, 'format'], ['1 5', 2, 'format'],
    ['١٢', 2, 'format'], ['15.005', 2, 'precision'], ['15.0', 0, 'precision'],
    ['0', 2, 'range'], ['0.00', 2, 'range'], ['10000000.01', 2, 'range'],
    ['1000000001', 0, 'range'], ['99999999999999999999999', 0, 'range'],
  ];
  for (const [text, mu, reason] of bad) assert.deepEqual(parseAmount(text, mu), { ok: false, reason }, String(text));
});

test('formatAmount / formatDecimal', () => {
  assert.equal(formatAmount(10000, 2, 'EUR'), '100.00 EUR');
  assert.equal(formatAmount(1200, 0, 'JPY'), '1200 JPY');
  assert.equal(formatAmount(5, 2, 'EUR'), '0.05 EUR');
  assert.equal(formatAmount(1, 3, 'BHD'), '0.001 BHD');
  assert.equal(formatAmount(0, 2, 'EUR'), '0.00 EUR');
  assert.equal(formatAmount(10n ** 12n, 2, 'EUR'), '10000000000.00 EUR');
  assert.equal(formatAmount('1550', 2, 'EUR'), '15.50 EUR');
  assert.equal(formatDecimal(2000, 2), '20.00');
  assert.equal(formatDecimal(2000, 0), '2000');
  assert.equal(formatDecimal(-150, 2), '-1.50');
});

test('parse then format round-trips', () => {
  for (const mu of [0, 2, 3]) {
    for (const minor of [1, 9, 10, 99, 100, 101, 123456789, 1000000000]) {
      const text = formatDecimal(minor, mu);
      assert.deepEqual(parseAmount(text, mu), { ok: true, minor }, `${text}@${mu}`);
    }
  }
});

test('splitShares: stage-1 section 9 examples', () => {
  assert.deepEqual(splitShares(1000, 3), [334, 333, 333]);
  assert.deepEqual(splitShares(1, 3), [1, 0, 0]);
  assert.deepEqual(splitShares(10, 3), [4, 3, 3]);
  assert.deepEqual(splitShares(999, 3), [333, 333, 333]);
  assert.deepEqual(splitShares(5, 5), [1, 1, 1, 1, 1]);
  assert.deepEqual(splitShares(5, 0), []);
});

// split-table.json is generated by round-robin dealing, independent of the closed form,
// and is also read by TestSplitSharesTable in split_table_test.go.
test('splitShares matches the shared table (amount 1..60, n 1..8)', () => {
  const table = JSON.parse(readFileSync(new URL('./split-table.json', import.meta.url), 'utf8'));
  assert.equal(table.length, 60 * 8);
  for (const { amount, n, shares } of table) {
    const got = splitShares(amount, n);
    assert.deepEqual(got, shares, `${amount}/${n}`);
    assert.equal(got.reduce((a, b) => a + b, 0), amount);
  }
});

test('parseHandles', () => {
  assert.deepEqual(parseHandles('bob, Carol ,,dave,'), ['bob', 'Carol', 'dave']);
  assert.deepEqual(parseHandles(' , ,'), []);
  assert.deepEqual(parseHandles(''), []);
  assert.deepEqual(parseHandles('bob,bob'), ['bob', 'bob']);
  assert.deepEqual(parseHandles('ada'), ['ada']);
});
